### ISSUE TITLE
Add converse.js

### ISSUE THREAD

**Issue by Perflyst** [ge0rg/easy-xmpp-invitation#18]
Add converse.js as webclient recommendation

**Comment by licaon-kter** [comment]
If the domain support it? Else it's not something that you can get...

**Comment by Perflyst** [comment]
We could link https://conversejs.org/fullscreen.html or https://inverse.chat/ where you can login with any account on any server.

**Comment by licaon-kter** [comment]
And JcBrand pinkie promises to not record credentials... I don't find nice...not as nice as a standalone client.

**Comment by Perflyst** [comment]
You are right, then lets wait for `Look out for an Electron based version of Converse coming in the following months.` https://conversejs.org/docs/html/features.html

**Comment by sjehuda** [comment]
> Add converse.js as webclient recommendation

Both, client and desktop.
Desktop, with all the others.
Webclient, for an immediate access

**Comment by ge0rg** [comment]
Fixed in #32

**Comment by sjehuda** [comment]
> Add converse.js as webclient recommendation

@Perflyst please explain why do (or did) you want to do this.
In what why would it be useful?
