### ISSUE TITLE
DOAP standard

### ISSUE THREAD

**Issue by sjehuda** [ge0rg/easy-xmpp-invitation#34]
#### intro

Why I'm _for_ using DOAP?
- Because it can be used as a standard to share data, similarly to XBEL and vCard.
- Because XML is a very robust filetype to transfer information.
- Because JSON is really unprofessional.
- ~~ If you disagree, I'll sue you in court. ~~

#### issue

As proposed by @Echolon at https://github.com/ge0rg/easy-xmpp-invitation/pull/32#issuecomment-1130198114

@ge0rg, please assign me for this task.

Design:
Add custom tags to link to app stores.
Use XPath to retrieve content.

**Comment by sjehuda** [comment]
@Echolon I need help in design.

## Problem

I can add a great amount of apps for each platform, which is what I'm going to do.
There are two problems:
- User might be flooded with an overwhelming list
- Some web admins will not know how to make their own selection other than deleting those that they don't want; some might as well want to have just a single choice.

## Proposal
Please note that we will have a DOAP file per client.

#### Question
How should we design the client selection mechanism?

##### Example:
Use a JSON file/array, similarly to how we do it right now, and according to JSON file, DOAP files will be retrieved accordingly.

##### For instance:
File: `clients_Android.json`
```
[
    "yaxim",
    "Conversation",
    "Xabber",
    "Bruno",
    "Monocles"
]
```
Will use files: `yaxim.doap` `conversation` `xabber.doap` `bruno.doap` `monocles.doap` (or `.rdf` or `.xml` whatever the file extension is)

What do you think?

**Comment by Echolon** [comment]
@sjehuda not easy the question. One thing we will have in the future I think is to evaluate the compliance level via doaps. Maybe go for the moment with entries that dont have outdated timestamps + are listed in the xmpp.org "Getting Started" page (afaik)

**Comment by sjehuda** [comment]
> I think is to evaluate the compliance level via doaps

Great idea. Thank you @Echolon 

I'll keep it at that, because I know how to approach the proposed design above in a concise and clear manner, and especially XPath-wise.

If anyone has an objection to the proposed design, please let me know.

**Comment by sjehuda** [comment]
Focusing on [yaxim](https://github.com/xsf/xmpp.org/blob/master/data/clients.json#L766)yaxim [yaxim.rdf.xml](https://yaxim.org/doap/yaxim.rdf.xml)

```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns="http://usefulinc.com/ns/doap#"
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xmlns:xmpp="https://linkmauve.fr/ns/xmpp-doap#"
        xmlns:foaf="http://xmlns.com/foaf/0.1/"
        xmlns:schema="https://schema.org/">
  <Project>

    <name>yaxim</name>

    <shortdesc xml:lang="en">yet another XMPP instant messenger</shortdesc>
    <description xml:lang="en">yaxim is an Android XMPP/Jabber client with a clean user interface and open source (GPLv3).</description>
    <schema:logo rdf:resource="https://yaxim.org/images/yaxim.svg"/>
    <schema:screenshot rdf:resource="https://yaxim.org/screenshots/tiny/roster.png"/>
    <schema:documentation rdf:resource="https://github.com/yaxim-org/yaxim/wiki"/>

    <homepage rdf:resource="https://yaxim.org/" />
    <wiki rdf:resource="https://github.com/yaxim-org/yaxim/wiki" />
    <bug-database rdf:resource="https://github.com/yaxim-org/yaxim/issues" />
    <category rdf:resource="https://linkmauve.fr/ns/xmpp-doap#category-client" />
    <category rdf:resource="http://api.gnome.org/doap-extensions#apps" />
    <license rdf:resource="http://usefulinc.com/doap/licenses/gplv3" />

    <programming-language>Java</programming-language>
    <os>Android</os>

    <repository>
      <GitRepository>
        <location rdf:resource="https://github.com/yaxim-org/yaxim.git" />
        <browse rdf:resource="https://github.com/yaxim-org/yaxim" />
      </GitRepository>
    </repository>

    <download>
      <play>
        <location rdf:resource="https://play.google.com/store/apps/details?id=org.yaxim.androidclient" />
        <browse rdf:resource="https://play.google.com/store/apps/details?id=org.yaxim.androidclient" />
      </play>
      <fdroid>
        <location rdf:resource="https://f-droid.org/packages/org.yaxim.androidclient/" />
        <browse rdf:resource="https://f-droid.org/packages/org.yaxim.androidclient/" />
      </fdroid>
      <fallback>
        <location rdf:resource="https://yaxim.org/archive/yaxim-bb.apk" />
        <browse rdf:resource="https://yaxim.org/archive/yaxim-bb.apk" />
      </fallback>
    </download>

  </Project>
</rdf:RDF>
```

I then retrieve the name from `<name>`, logo from `<schema:logo>` and description from `<description>` and the the download links from <download>.

My question is, what JS mechanism (on cliebnt side) do we have that would allow XSS, that is to check for status 200 for 3rd part links?



_P.S. Awesome work on the [XSL style](https://yaxim.org/doap/style.xsl)!_

**Comment by ge0rg** [comment]
Maybe we need some server-side code to download the DOAP files and provide an extract of the data. We don't need this much anyway from them, so this could be done periodically by a job that would populate clients_XYZ.json

**Comment by Echolon** [comment]
> Maybe we need some server-side code to download the DOAP files and provide an extract of the data. We don't need this much anyway from them, so this could be done periodically by a job that would populate clients_XYZ.json

Stupod question: Isn't the xsf client.json what you need if you just query the top keys?

**Comment by mwild1** [comment]
This is the code that xmpp.org uses to fetch and extract info from DOAP files (including logos): https://github.com/xsf/xmpp.org/blob/master/tools/prepare_software_list.py

**Comment by sjehuda** [comment]
The DOAP files might be useful when they have "available languages" of which a program is available in.

**Comment by sjehuda** [comment]
The compliance concern is valid, but is relevant when we don't do a manual check, which is what we are doing right now by sending code  and discussing about it.

We might want to use `INI`, `YAML` files instead.

I'm closing this.
