### ISSUE TITLE
English text

### ISSUE THREAD

**Issue by sjehuda** [ge0rg/easy-xmpp-invitation#44]
What does this mean?
> XMPP is a provider independent form of instant messaging.

Proposed change:
```diff
- "xmppis": "XMPP is a provider independent form of instant messaging.  You can pick from many different clients and have a free choice of server operators to participate.",
+ "xmppis": "XMPP provides an independent form of instant messaging.  You can pick from many different clients and have a free choice of server operators to participate.",
```

I'm posting here, not for approval as I can use a PR for this, I'm posting this too get feedback.

**Comment by licaon-kter** [comment]
"provider independent" means "does not depend on provider"

Your rewrite sounds odd imho

**Comment by sjehuda** [comment]
OK.

Should we add a hyphen? (i.e. provider-independent)
