### ISSUE TITLE
Support and display the `name=` query parameter

### ISSUE THREAD

**Issue by ge0rg** [ge0rg/easy-xmpp-invitation#5]
Currently, the displayed name is derived from the JID. A sender might want to append a `&name=Donnie` parameter to the xmpp: URI to specify the display name.

This parameter should be parsed in `load_hash()` and used as the display name. It might be also useful to proivde a clearer display of the JID (as this has security implications).

**Comment by ge0rg** [comment]
Out of the top of my head:

* for a contact request that you await ("Mom"), you can check if Mom's actually on your private server and has the right user name, or is mallory@jabber.ru

* for MUCs: if the MUC is hosted on your server, it's less prone to manipulations

**Comment by strugee** [comment]
Ah yes. Right on.
