### ISSUE TITLE
Display QR code 

### ISSUE THREAD

**Issue by ge0rg** [ge0rg/easy-xmpp-invitation#6]
The invitation page should also render a QR code when displayed on a desktop system, in a privacy conserving way.

**Comment by wiktor-k** [comment]
QR Code can be rendered via JavaScript using this library: https://github.com/davidshimjs/qrcodejs

The API is extremely small:

```js
new QRCode(document.getElementById("qrcode"), "xmpp:test@example.com");
```

**Comment by ge0rg** [comment]
That's a good catch. It would be good to have some conditional loading based on whether we are on mobile or on desktop, and to display the QR code on the desktop only by default.

**Comment by wiktor-k** [comment]
> conditional loading based on whether we are on mobile or on desktop

That could be tricky as there are numerous detection techniques, each one with their own (dis)advantages. Maybe "Show QR code" button? Expandable section? I'm not UI expert unfortunately :)

**Comment by ge0rg** [comment]
:+1: for a "Show QR code" button. Though I think this is not the most urgent problem of this project ;-)

If you are inclined, have a look at the README's TODO section :)

**Comment by stevenroose** [comment]
Just showing the QR code always is better than never IMHO.

**Comment by ge0rg** [comment]
@stevenroose the challenge of good design is to only show what's actually needed. I try hard to remove everything that's not strictly required from the landing page, because it's too complex already.
