### ISSUE TITLE
Readonly input for XMPP address

### ISSUE THREAD

**Issue by wiktor-k** [ge0rg/easy-xmpp-invitation#7]
Hello,

Should this input have `readonly` attribute?

https://github.com/ge0rg/easy-xmpp-invitation/blob/19405cb5c738f5f8497f863e9434b431084ba06c/index.html#L28

Changing it has no effect and can be confusing, if there is no other reason for it to be writable.

**Comment by ge0rg** [comment]
It would be great to have some logic, where it is possible to set a new xmpp: URI / manually inivte people. However that would probably need a different UI, so the answer to your question is "yes" :)
